version: "2"
linters:
  enable:
    - exhaustive
    - goconst
    - godox
    - lll
    - misspell
    - mnd
  settings:
    lll:
      line-length: 228
      tab-width: 8
    staticcheck:
      checks:
        - SA1019
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        path: .*
        text: SA1019
      - linters:
          - staticcheck
        path: .*
        text: ST1003 # should not use ALL_CAPS in Go names; use CamelCase instead
      - linters:
          - staticcheck
        path: .*
        text: ST1005 # error strings should not be capitalized
      - linters:
          - staticcheck
        path: .*
        text: ST1016 # methods on the same type should have the same receiver name
      - linters:
          - staticcheck
        path: .*
        text: ST1019 # package is being imported more than once
      - linters:
          - staticcheck
        path: .*
        text: ST1023 # should omit type from declaration; it will be inferred from the right-hand side
      - linters:
          - staticcheck
        path: .*
        text: QF1003 # could use tagged switch
      - linters:
          - staticcheck
        path: .*
        text: QF1004 # could use strings.ReplaceAll instead
      - linters:
          - staticcheck
        path: .*
        text: QF1011 # could omit type error from declaration; it will be inferred from the right-hand side
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
