version: "2"
linters:
  enable:
    - exhaustive
    - goconst
    - godox
    - lll
    - misspell
    - mnd
  settings:
    lll:
      line-length: 228
      tab-width: 8
    staticcheck:
      checks:
        - SA1019
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        path: .*
        text: SA1019
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
