name: Release
on:
    push:
        branches:
            - main
            # - release/*
            - prerelease/*
permissions:
    actions: write
    contents: write
    id-token: write
    # packages: write
    pull-requests: write
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        # outputs:
            # published: ${{ steps.changeset.outputs.published }}
            # publishedPackages: ${{ steps.changeset.outputs.publishedPackages }}
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: pnpm/action-setup@v4
            - name: Setup Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1

            - name: Install Dependencies
              run: pnpm install

            - name: Determine Version Type
              id: version-type
              run: |
                if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
                    echo "VERSION_TYPE=stable" >> $GITHUB_ENV
                    elif [[ "${{ github.ref }}" =~ ^refs/heads/prerelease/ ]]; then
                    echo "VERSION_TYPE=alpha" >> $GITHUB_ENV
                fi
                echo $VERSION_TYPE
            - name: Create Release Pull Request
              id: changeset
              uses: changesets/action@v1
              with:
                  commit: "release: version packages"
                  publish: pnpm run publish-packages
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}